### PR TITLE
code refactoring and bugfixes

### PR DESCRIPTION
**Pull request by vapniks**
Do you want me to take over maintenance of this library?
You asked me before and I said no, but I've made so many changes now and got to know the code so I don't mind.

### CODE REVIEW

**Comment by mattfidler** [comment]
I would like that. I'm unsure how to do that, though

**Comment by mattfidler** [comment]
This branch reqiures some bug resolution,  so I didnt merge it.  I wont have computer access until next Monday.

**Comment by vapniks** [comment]
https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by mattfidler** [comment]
You are now a collaborator.  You can resolve the conflict and merge, or I will do it next week.

**Comment by vapniks** [comment]
done

**Comment by mattfidler** [comment]
Thanks @vapniks

**Pull request merged**
